version: '3.9'

services:
  pg:
    image: postgres:latest
    restart: always
    container_name: Portfolio_db_cont
    environment:
      - POSTGRES_DB=Portfolio_db
      - POSTGRES_PASSWORD=black090
      - POSTGRES_USER=postgres
      - PORT=5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    build: .
    restart: always
    container_name: Web_cont
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/apps
    ports:
      - "8000:8000"
    depends_on:
      - pg

volumes:
  pg_data:
    